### ISSUE TITLE
Uploading beta managed package via Selenium Fails Due to Timeout

### ISSUE THREAD

**Issue by almostthor** [SalesforceFoundation/CumulusCI#105]
It appears that the upload beta is failing because Selenium is having to wait more than 90 seconds to see the VersionInfoSectionItem:VersionText show up in the DOM.

```
Traceback (most recent call last):
File "../CumulusCI/ci/package_upload.py", line 249, in <module>
package_upload()
File "../CumulusCI/ci/package_upload.py", line 233, in package_upload
uploader.build_package(build_name)
File "../CumulusCI/ci/package_upload.py", line 146, in build_package
name_input = driver.find_element_by_id('ExportPackagePage:UploadPackageForm:PackageDetailsPageBlock:PackageDetailsBlockSection:VersionInfoSectionItem:VersionText')
File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 206, in find_element_by_id
return self.find_element(by=By.ID, value=id_)
File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 662, in find_element
{'using': by, 'value': value})['value']
File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 173, in execute
self.error_handler.check_response(response)
File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 166, in check_response
raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: {"method":"id","selector":"ExportPackagePage:UploadPackageForm:PackageDetailsPageBlock:PackageDetailsBlockSection:VersionInfoSectionItem:VersionText"}
Stacktrace:
at FirefoxDriver.prototype.findElementInternal_ (file:///tmp/tmpGKjSbl/extensions/fxdriver@googlecode.com/components/driver-component.js:9641:7)
at fxdriver.Timer.prototype.setTimeout/<.notify (file:///tmp/tmpGKjSbl/extensions/fxdriver@googlecode.com/components/driver-component.js:548:5)
```

**Comment by jlantz** [comment]
Closing out an old issue to make way for CumulusCI 2.

For future reference, CumulusCI 2 no longer supports the Selenium package upload process.  Instead, you can use `cci task run upload_beta` to upload a beta release using PackageUploadRequest (pilot) via the Tooling API.
