### ISSUE TITLE
C2  - Connected App -- ValueError: AES key must be either 16, 24, or 32 bytes long

### ISSUE THREAD

**Issue by TedHusted** [SalesforceFoundation/CumulusCI#157]
I've been walking through the setup instructions for CumulusCI2, with a clone from today, but I'm blocked at the connected app setup,
- https://github.com/SalesforceFoundation/CumulusCI/tree/feature/2.0

When I complete the setup and circle back to the Quick Start, the script indicates a connected app. 

I followed the setup instructions at
- https://cumulusci-oauth-tool.herokuapp.com

and exposed "ValueError: AES key must be either 16, 24, or 32 bytes long"

Traceback (most recent call last):
  File "/Users/thusted/github/CumulusCI/venv/bin/cumulusci2", line 11, in <module>
    load_entry_point('cumulusci', 'console_scripts', 'cumulusci2')()
  File "/Users/thusted/github/CumulusCI/venv/lib/python2.7/site-packages/click/core.py", line 716, in **call**
    return self.main(_args, *_kwargs)
  File "/Users/thusted/github/CumulusCI/venv/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/thusted/github/CumulusCI/venv/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/thusted/github/CumulusCI/venv/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/thusted/github/CumulusCI/venv/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, *_ctx.params)
  File "/Users/thusted/github/CumulusCI/venv/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(_args, *_kwargs)
  File "/Users/thusted/github/CumulusCI/venv/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], *_kwargs)
  File "/Users/thusted/github/CumulusCI/venv/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(_args, *_kwargs)
  File "/Users/thusted/github/CumulusCI/newcli/cumulusci.py", line 200, in org_config_connected_app
    config.keychain.set_connected_app(app_config)
  File "/Users/thusted/github/CumulusCI/core/keychain.py", line 42, in set_connected_app
    self._set_connected_app(app_config)
  File "/Users/thusted/github/CumulusCI/core/keychain.py", line 83, in _set_connected_app
    encrypted = self._encrypt_config(app_config)
  File "/Users/thusted/github/CumulusCI/core/keychain.py", line 113, in _encrypt_config
    cipher, iv = self._get_cipher()
  File "/Users/thusted/github/CumulusCI/core/keychain.py", line 106, in _get_cipher
    cipher = AES.new(self.key, AES.MODE_CBC, iv)
  File "/Users/thusted/github/CumulusCI/venv/lib/python2.7/site-packages/Crypto/Cipher/AES.py", line 95, in new
    return AESCipher(key, _args, *_kwargs)
  File "/Users/thusted/github/CumulusCI/venv/lib/python2.7/site-packages/Crypto/Cipher/AES.py", line 59, in __init__
    blockalgo.BlockAlgo.**init**(self, _AES, key, _args, *_kwargs)
  File "/Users/thusted/github/CumulusCI/venv/lib/python2.7/site-packages/Crypto/Cipher/blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, _args, *_kwargs)

**Comment by cdcarter** [comment]
Hey @TedHusted - not sure if you're still trying to get going with cumulusci2 but if you are, I think this error message has gotten a *little* bit better by now. You should be able to get up and running by setting the CUMULUSCI_KEY environment variable to a sixteen byte string. I'll try and get a patch to the docs in soon.

**Comment by davisagli** [comment]
The current docs mention that a 16-character key is required (https://cumulusci.readthedocs.io/en/latest/tutorial.html#keychain-key), so I think we can close this.
