### ISSUE TITLE
Receiving error upon pip install cumulusci

### ISSUE THREAD

**Issue by mvogelgesang** [SalesforceFoundation/CumulusCI#210]
going through the Installation Instructions, I hit an error when PyCrypto tried to be installed. I tried updating Crytpography but it failed to resolve the issue. I am running virtualenv and am on OS Sierra 10.12.2. Full stack below.

````
Building wheels for collected packages: PyCrypto
  Running setup.py bdist_wheel for PyCrypto ... error
  Complete output from command /Users/markvogelgesang/cumulusci_venv/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/8x/fynn007s1b3bzwtm9ybn9zh80000gp/T/pip-build-sisaEw/PyCrypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/8x/fynn007s1b3bzwtm9ybn9zh80000gp/T/tmpcJ5Gnkpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.11-x86_64-2.7
  creating build/lib.macosx-10.11-x86_64-2.7/Crypto
  copying lib/Crypto/__init__.py -> build/lib.macosx-10.11-x86_64-2.7/Crypto
  copying lib/Crypto/pct_warnings.py -> build/lib.macosx-10.11-x86_64-2.7/Crypto
  creating build/lib.macosx-10.11-x86_64-2.7/Crypto/Hash
  copying lib/Crypto/Hash/__init__.py -> build/lib.macosx-10.11-x86_64-2.7/Crypto/Hash
  copying lib/Crypto/Hash/hashalgo.py -> build/lib.macosx-10.11-x86_64-2.7/Crypto/Hash
  copying lib/Crypto/Hash/HMAC.py -> build/lib.macosx-10.11-x86_64-2.7/Crypto/Hash
  copying lib/Crypto/Hash/MD2.py -> build/lib.macosx-10.11-x86_64-2.7/Crypto/Hash
  copying lib/Crypto/Hash/MD4.py -> build/lib.macosx-10.11-x86_64-2.7/Crypto/Hash
  copying lib/Crypto/Hash/MD5.py -> build/lib.macosx-10.11-x86_64-2.7/Crypto/Hash
  copying lib/Crypto/Hash/RIPEMD.py -> build/lib.macosx-10.11-x86_64-2.7/Crypto/Hash
  copying lib/Crypto/Hash/SHA.py -> build/lib.macosx-10.11-x86_64-2.7/Crypto/Hash
  copying lib/Crypto/Hash/SHA224.py -> build/lib.macosx-10.11-x86_64-2.7/Crypto/Hash
  copying lib/Crypto/Hash/SHA256.py -> build/lib.macosx-10.11-x86_64-2.7/Crypto/Hash
  copying lib/Crypto/Hash/SHA384.py -> build/lib.macosx-10.11-x86_64-2.7/Crypto/Hash
  copying lib/Crypto/Hash/SHA512.py -> build/lib.macosx-10.11-x86_64-2.7/Crypto/Hash
  creating build/lib.macosx-10.11-x86_64-2.7/Crypto/Cipher
  ....
  running build_ext
  running build_configure
  checking for gcc... gcc
  checking whether the C compiler works... no
  configure: error: in `/private/var/folders/8x/fynn007s1b3bzwtm9ybn9zh80000gp/T/pip-build-sisaEw/PyCrypto':
  configure: error: C compiler cannot create executables
  See `config.log' for more details
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/8x/fynn007s1b3bzwtm9ybn9zh80000gp/T/pip-build-sisaEw/PyCrypto/setup.py", line 456, in <module>
      core.setup(**kw)
    File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/Users/markvogelgesang/cumulusci_venv/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/private/var/folders/8x/fynn007s1b3bzwtm9ybn9zh80000gp/T/pip-build-sisaEw/PyCrypto/setup.py", line 251, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/private/var/folders/8x/fynn007s1b3bzwtm9ybn9zh80000gp/T/pip-build-sisaEw/PyCrypto/setup.py", line 278, in run
      raise RuntimeError("autoconf error")
  RuntimeError: autoconf error
  
  ----------------------------------------
  Failed building wheel for PyCrypto
  Running setup.py clean for PyCrypto
Failed to build PyCrypto
````

**Comment by cdcarter** [comment]
Have you run:
`xcode-select --install`?
before your pip install?

**Comment by mvogelgesang** [comment]
@cdcarter **face palm** thanks! It's up and running!

**Comment by cdcarter** [comment]
Glad to hear that helped! Let me know if you run into any questions or issues with the tool.
