### ISSUE TITLE
C2 - IndexError exception in uninstall_packaged_incremental task when processing componentFailures from DeployResult

### ISSUE THREAD

**Issue by dospromptman** [SalesforceFoundation/CumulusCI#215]
CumulusCI 2 attempts to read `lineNumber` child element from `componentFailures` section of `DeployResult` message.  However, in my case, `lineNumber` did not exist in the `DeployResult` message, causing an IndexError exception.

Checking the Metadata API WSDL, it looks like `lineNumber` and a few others that CumulusCI 2 assumes exist, are actually optional elements.

Output log including stack trace:

```
(cumulusci_venv)  $ cci flow run dev_org --debug
2017-01-17 20:29:09: ---------------------------------------
2017-01-17 20:29:09: Initializing flow class BaseFlow:
2017-01-17 20:29:09: ---------------------------------------
2017-01-17 20:29:09: Flow Description: Deploys the unmanaged package metadata and all dependencies to the target org
2017-01-17 20:29:09: Tasks:
2017-01-17 20:29:09:   create_package: Creates a package in the target org with the default package name for the project
2017-01-17 20:29:09:   deploy_pre: Deploys all metadata bundles under unpackaged/pre/
2017-01-17 20:29:09:   update_dependencies: Installs all dependencies in project__dependencies into the target org
2017-01-17 20:29:09:   deploy: Deploys the src directory of the repository to the org
2017-01-17 20:29:09:   uninstall_packaged_incremental: Deletes any metadata from the package in the target org not in the local workspace
2017-01-17 20:29:09:   deploy_post: Deploys all metadata bundles under unpackaged/post/
2017-01-17 20:29:09:   update_admin_profile: Retrieves, edits, and redeploys the Admin.profile with full FLS perms for all objects/fields
2017-01-17 20:29:09:
2017-01-17 20:29:09: Running task: create_package
2017-01-17 20:29:10: Options:
2017-01-17 20:29:10:   api_version: 38.0
2017-01-17 20:29:10:   package: SAL
2017-01-17 20:29:10: Pending
2017-01-17 20:29:14: [Done]
2017-01-17 20:29:15: [Success]: Succeeded
2017-01-17 20:29:15: Task complete: create_package
2017-01-17 20:29:15:
2017-01-17 20:29:15: Running task: deploy_pre
2017-01-17 20:29:16: Options:
2017-01-17 20:29:16:   path: unpackaged/pre
2017-01-17 20:29:16: Deploying all metadata bundles in path /Users/jbury/Documents/sal/unpackaged/pre
2017-01-17 20:29:16: Deploying bundle: unpackaged/pre/acc_record_types
2017-01-17 20:29:16: Pending
2017-01-17 20:29:16: [Pending]: next check in 1 seconds
2017-01-17 20:29:17: [InProgress]: Processing Type: CustomObject
2017-01-17 20:29:20: [Done]
2017-01-17 20:29:22: [Success]: Succeeded
2017-01-17 20:29:22: Deploying bundle: unpackaged/pre/contact_key_affl_fields
2017-01-17 20:29:22: Pending
2017-01-17 20:29:23: [Pending]: next check in 1 seconds
2017-01-17 20:29:24: [InProgress]: Processing Type: CustomObject
2017-01-17 20:29:25: [InProgress]: Processing Type: CustomObject
2017-01-17 20:29:28: [Done]
2017-01-17 20:29:30: [Success]: Succeeded
2017-01-17 20:29:30: Task complete: deploy_pre
2017-01-17 20:29:30:
2017-01-17 20:29:30: Running task: update_dependencies
2017-01-17 20:29:30: Options:
2017-01-17 20:29:30: Retrieving list of packages from target org
2017-01-17 20:29:30: Pending
2017-01-17 20:29:31: [Pending]: next check in 1 seconds
2017-01-17 20:29:32: [Done]
2017-01-17 20:29:33: Dependencies:
2017-01-17 20:29:33:   hed: version 1.26 already installed
2017-01-17 20:29:33: Task complete: update_dependencies
2017-01-17 20:29:33:
2017-01-17 20:29:33: Running task: deploy
2017-01-17 20:29:36: Options:
2017-01-17 20:29:36:   path: src
2017-01-17 20:29:36: Pending
2017-01-17 20:29:37: [Pending]: next check in 1 seconds
2017-01-17 20:29:38: [Pending]: next check in 1 seconds
2017-01-17 20:29:40: [InProgress]: Processing Type: AuraDefinitionBundle
2017-01-17 20:29:42: [InProgress]: Processing Type: CustomObject
2017-01-17 20:29:44: [InProgress]: Processing Type: ApexClass
2017-01-17 20:29:47: [InProgress]: Processing Type: ContentAsset
2017-01-17 20:29:50: [InProgress]: Processing Type: ContentAsset
2017-01-17 20:29:53: [InProgress]: Processing Type: ContentAsset
2017-01-17 20:29:56: [InProgress]: Processing Type: ContentAsset
2017-01-17 20:30:01: [Pending]: next check in 4 seconds
2017-01-17 20:30:05: [Done]
2017-01-17 20:30:09: [Success]: Succeeded
2017-01-17 20:30:09: Task complete: deploy
2017-01-17 20:30:09:
2017-01-17 20:30:09: Running task: uninstall_packaged_incremental
2017-01-17 20:30:10: Options:
2017-01-17 20:30:10:   purge_on_delete: True
2017-01-17 20:30:10:   path: src
2017-01-17 20:30:10:   package: SAL
2017-01-17 20:30:10: Retrieving metadata in package SAL from target org
2017-01-17 20:30:10: Pending
2017-01-17 20:30:10: [Pending]: next check in 1 seconds
2017-01-17 20:30:12: [Pending]: next check in 1 seconds
2017-01-17 20:30:14: [Pending]: next check in 2 seconds
2017-01-17 20:30:16: [Done]
2017-01-17 20:30:22: Deleting metadata:
2017-01-17 20:30:22:     Layout: Appt_Location__mdt-Appt Location Layout
2017-01-17 20:30:22:     CommunityTemplateDefinition: Advisor_Link
2017-01-17 20:30:22:     CustomMetadata: Appt_Location.in_person
2017-01-17 20:30:22:     CustomMetadata: Appt_Location.online
2017-01-17 20:30:22:     CustomObject: Appt_Location__mdt
2017-01-17 20:30:22:     AuraDefinitionBundle: autocomplete
2017-01-17 20:30:22:     AuraDefinitionBundle: autocompleteContext
2017-01-17 20:30:22:     AuraDefinitionBundle: autocompleteOption
2017-01-17 20:30:22:     AuraDefinitionBundle: autocompleteSelectListOption
2017-01-17 20:30:22:     AuraDefinitionBundle: dataProviderInterface
2017-01-17 20:30:22:     AuraDefinitionBundle: lookup
2017-01-17 20:30:22:     AuraDefinitionBundle: lookupPill
2017-01-17 20:30:22:     AuraDefinitionBundle: lookupPillRemove
2017-01-17 20:30:22:     CommunityThemeDefinition: Advisor_Link
2017-01-17 20:30:22:     StaticResource: siteAsset_c026449691e7463c9abe14f98e87c5f1
2017-01-17 20:30:22:     FlexiPage: Advisor_Link_Article_Detail
2017-01-17 20:30:22:     FlexiPage: Advisor_Link_Contact_Support
2017-01-17 20:30:22:     FlexiPage: Advisor_Link_Create_Record
2017-01-17 20:30:22:     FlexiPage: Advisor_Link_Error
2017-01-17 20:30:22:     FlexiPage: Advisor_Link_Feed_Detail
2017-01-17 20:30:22:     FlexiPage: Advisor_Link_Group_Detail
2017-01-17 20:30:22:     FlexiPage: Advisor_Link_Group_List
2017-01-17 20:30:22:     FlexiPage: Advisor_Link_Home
2017-01-17 20:30:22:     FlexiPage: Advisor_Link_Question_Detail
2017-01-17 20:30:22:     FlexiPage: Advisor_Link_Record_Detail
2017-01-17 20:30:22:     FlexiPage: Advisor_Link_Record_List
2017-01-17 20:30:22:     FlexiPage: Advisor_Link_Related_Record_List
2017-01-17 20:30:22:     FlexiPage: Advisor_Link_Report_Detail
2017-01-17 20:30:22:     FlexiPage: Advisor_Link_Search
2017-01-17 20:30:22:     FlexiPage: Advisor_Link_Sfdc_Page
2017-01-17 20:30:22:     FlexiPage: Advisor_Link_Topic_Catalog
2017-01-17 20:30:22:     FlexiPage: Advisor_Link_Topic_Detail
2017-01-17 20:30:22:     FlexiPage: Advisor_Link_User_Profile
2017-01-17 20:30:22:     FlexiPage: Advisor_Link_User_Settings
2017-01-17 20:30:22:     FlexiPage: Advisor_Link_appt_type
2017-01-17 20:30:22:     FlexiPage: Advisor_Link_napili_themeLayout_home
2017-01-17 20:30:22:     ApexClass: Default_TEST
2017-01-17 20:30:22: Deleting metadata in package SAL from target org
2017-01-17 20:30:22: Pending
2017-01-17 20:30:22: [Pending]: next check in 1 seconds
2017-01-17 20:30:24: [Pending]: next check in 1 seconds
2017-01-17 20:30:25: [Pending]: next check in 2 seconds
2017-01-17 20:30:27: [Pending]: next check in 2 seconds
2017-01-17 20:30:29: [Done]
2017-01-17 20:30:31: Task failed: uninstall_packaged_incremental
2017-01-17 20:30:31: Failing flow due to exception in task
Traceback (most recent call last):
  File "/Users/jbury/cumulusci_venv/lib/python2.7/site-packages/cumulusci/newcli/cli.py", line 738, in flow_run
    flow()
  File "/Users/jbury/cumulusci_venv/lib/python2.7/site-packages/cumulusci/core/flows.py", line 66, in __call__
    self._run_task(flow_task_config)
  File "/Users/jbury/cumulusci_venv/lib/python2.7/site-packages/cumulusci/core/flows.py", line 117, in _run_task
    response = task()
  File "/Users/jbury/cumulusci_venv/lib/python2.7/site-packages/cumulusci/core/tasks.py", line 56, in __call__
    res = self._run_task()
  File "/Users/jbury/cumulusci_venv/lib/python2.7/site-packages/cumulusci/tasks/salesforce.py", line 60, in _run_task
    return api()
  File "/Users/jbury/cumulusci_venv/lib/python2.7/site-packages/cumulusci/salesforce_api/metadata.py", line 45, in __call__
    return self._process_response(response)
  File "/Users/jbury/cumulusci_venv/lib/python2.7/site-packages/cumulusci/salesforce_api/metadata.py", line 410, in _process_response
    'line_num': component_failure.getElementsByTagName('lineNumber')[0].firstChild.nodeValue,
IndexError: list index out of range
> /Users/jbury/cumulusci_venv/lib/python2.7/site-packages/cumulusci/salesforce_api/metadata.py(410)_process_response()
-> 'line_num': component_failure.getElementsByTagName('lineNumber')[0].firstChild.nodeValue,
```

Retrieved the DeployResult response from Pdb:

```xml
<?xml version="1.0"?>
<soapenv:Envelope xmlns="http://soap.sforce.com/2006/04/metadata" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
  <soapenv:Body>
    <checkDeployStatusResponse>
      <result>
        <checkOnly>false</checkOnly>
        <completedDate>2017-01-18T02:30:28.000Z</completedDate>
        <createdBy>005B0000002XoBf</createdBy>
        <createdByName>Jason Bury</createdByName>
        <createdDate>2017-01-18T02:30:22.000Z</createdDate>
        <details>
          <componentFailures>
            <changed>false</changed>
            <componentType>CommunityThemeDefinition</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:27.000Z</createdDate>
            <deleted>false</deleted>
            <fileName>communityThemeDefinitions/Advisor_Link.communityThemeDefinition</fileName>
            <fullName>Advisor_Link</fullName>
            <problem>id does not exist</problem>
            <problemType>Error</problemType>
            <success>false</success>
          </componentFailures>
          <componentFailures>
            <changed>false</changed>
            <componentType>FlexiPage</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:27.000Z</createdDate>
            <deleted>false</deleted>
            <fileName>flexipages/Advisor_Link_Home.flexipage</fileName>
            <fullName>Advisor_Link_Home</fullName>
            <problem>id does not exist</problem>
            <problemType>Error</problemType>
            <success>false</success>
          </componentFailures>
          <componentFailures>
            <changed>false</changed>
            <componentType>FlexiPage</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:27.000Z</createdDate>
            <deleted>false</deleted>
            <fileName>flexipages/Advisor_Link_Report_Detail.flexipage</fileName>
            <fullName>Advisor_Link_Report_Detail</fullName>
            <problem>id does not exist</problem>
            <problemType>Error</problemType>
            <success>false</success>
          </componentFailures>
          <componentFailures>
            <changed>false</changed>
            <componentType>FlexiPage</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:27.000Z</createdDate>
            <deleted>false</deleted>
            <fileName>flexipages/Advisor_Link_Topic_Detail.flexipage</fileName>
            <fullName>Advisor_Link_Topic_Detail</fullName>
            <problem>id does not exist</problem>
            <problemType>Error</problemType>
            <success>false</success>
          </componentFailures>
          <componentFailures>
            <changed>false</changed>
            <componentType>FlexiPage</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:27.000Z</createdDate>
            <deleted>false</deleted>
            <fileName>flexipages/Advisor_Link_Search.flexipage</fileName>
            <fullName>Advisor_Link_Search</fullName>
            <problem>id does not exist</problem>
            <problemType>Error</problemType>
            <success>false</success>
          </componentFailures>
          <componentFailures>
            <changed>false</changed>
            <componentType>FlexiPage</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:27.000Z</createdDate>
            <deleted>false</deleted>
            <fileName>flexipages/Advisor_Link_Question_Detail.flexipage</fileName>
            <fullName>Advisor_Link_Question_Detail</fullName>
            <problem>id does not exist</problem>
            <problemType>Error</problemType>
            <success>false</success>
          </componentFailures>
          <componentFailures>
            <changed>false</changed>
            <componentType>FlexiPage</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:27.000Z</createdDate>
            <deleted>false</deleted>
            <fileName>flexipages/Advisor_Link_Feed_Detail.flexipage</fileName>
            <fullName>Advisor_Link_Feed_Detail</fullName>
            <problem>id does not exist</problem>
            <problemType>Error</problemType>
            <success>false</success>
          </componentFailures>
          <componentFailures>
            <changed>false</changed>
            <componentType>FlexiPage</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:27.000Z</createdDate>
            <deleted>false</deleted>
            <fileName>flexipages/Advisor_Link_appt_type.flexipage</fileName>
            <fullName>Advisor_Link_appt_type</fullName>
            <problem>id does not exist</problem>
            <problemType>Error</problemType>
            <success>false</success>
          </componentFailures>
          <componentFailures>
            <changed>false</changed>
            <componentType>FlexiPage</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:27.000Z</createdDate>
            <deleted>false</deleted>
            <fileName>flexipages/Advisor_Link_Related_Record_List.flexipage</fileName>
            <fullName>Advisor_Link_Related_Record_List</fullName>
            <problem>id does not exist</problem>
            <problemType>Error</problemType>
            <success>false</success>
          </componentFailures>
          <componentFailures>
            <changed>false</changed>
            <componentType>FlexiPage</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:27.000Z</createdDate>
            <deleted>false</deleted>
            <fileName>flexipages/Advisor_Link_Create_Record.flexipage</fileName>
            <fullName>Advisor_Link_Create_Record</fullName>
            <problem>id does not exist</problem>
            <problemType>Error</problemType>
            <success>false</success>
          </componentFailures>
          <componentFailures>
            <changed>false</changed>
            <componentType>FlexiPage</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:27.000Z</createdDate>
            <deleted>false</deleted>
            <fileName>flexipages/Advisor_Link_Article_Detail.flexipage</fileName>
            <fullName>Advisor_Link_Article_Detail</fullName>
            <problem>id does not exist</problem>
            <problemType>Error</problemType>
            <success>false</success>
          </componentFailures>
          <componentFailures>
            <changed>false</changed>
            <componentType>FlexiPage</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:27.000Z</createdDate>
            <deleted>false</deleted>
            <fileName>flexipages/Advisor_Link_Topic_Catalog.flexipage</fileName>
            <fullName>Advisor_Link_Topic_Catalog</fullName>
            <problem>id does not exist</problem>
            <problemType>Error</problemType>
            <success>false</success>
          </componentFailures>
          <componentFailures>
            <changed>false</changed>
            <componentType>FlexiPage</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:27.000Z</createdDate>
            <deleted>false</deleted>
            <fileName>flexipages/Advisor_Link_User_Settings.flexipage</fileName>
            <fullName>Advisor_Link_User_Settings</fullName>
            <problem>id does not exist</problem>
            <problemType>Error</problemType>
            <success>false</success>
          </componentFailures>
          <componentFailures>
            <changed>false</changed>
            <componentType>FlexiPage</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:27.000Z</createdDate>
            <deleted>false</deleted>
            <fileName>flexipages/Advisor_Link_Record_Detail.flexipage</fileName>
            <fullName>Advisor_Link_Record_Detail</fullName>
            <problem>id does not exist</problem>
            <problemType>Error</problemType>
            <success>false</success>
          </componentFailures>
          <componentFailures>
            <changed>false</changed>
            <componentType>FlexiPage</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:27.000Z</createdDate>
            <deleted>false</deleted>
            <fileName>flexipages/Advisor_Link_Contact_Support.flexipage</fileName>
            <fullName>Advisor_Link_Contact_Support</fullName>
            <problem>id does not exist</problem>
            <problemType>Error</problemType>
            <success>false</success>
          </componentFailures>
          <componentFailures>
            <changed>false</changed>
            <componentType>FlexiPage</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:27.000Z</createdDate>
            <deleted>false</deleted>
            <fileName>flexipages/Advisor_Link_Group_Detail.flexipage</fileName>
            <fullName>Advisor_Link_Group_Detail</fullName>
            <problem>id does not exist</problem>
            <problemType>Error</problemType>
            <success>false</success>
          </componentFailures>
          <componentFailures>
            <changed>false</changed>
            <componentType>FlexiPage</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:27.000Z</createdDate>
            <deleted>false</deleted>
            <fileName>flexipages/Advisor_Link_User_Profile.flexipage</fileName>
            <fullName>Advisor_Link_User_Profile</fullName>
            <problem>id does not exist</problem>
            <problemType>Error</problemType>
            <success>false</success>
          </componentFailures>
          <componentFailures>
            <changed>false</changed>
            <componentType>FlexiPage</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:27.000Z</createdDate>
            <deleted>false</deleted>
            <fileName>flexipages/Advisor_Link_Error.flexipage</fileName>
            <fullName>Advisor_Link_Error</fullName>
            <problem>id does not exist</problem>
            <problemType>Error</problemType>
            <success>false</success>
          </componentFailures>
          <componentFailures>
            <changed>false</changed>
            <componentType>FlexiPage</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:27.000Z</createdDate>
            <deleted>false</deleted>
            <fileName>flexipages/Advisor_Link_Record_List.flexipage</fileName>
            <fullName>Advisor_Link_Record_List</fullName>
            <problem>id does not exist</problem>
            <problemType>Error</problemType>
            <success>false</success>
          </componentFailures>
          <componentFailures>
            <changed>false</changed>
            <componentType>FlexiPage</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:28.000Z</createdDate>
            <deleted>false</deleted>
            <fileName>flexipages/Advisor_Link_Sfdc_Page.flexipage</fileName>
            <fullName>Advisor_Link_Sfdc_Page</fullName>
            <problem>id does not exist</problem>
            <problemType>Error</problemType>
            <success>false</success>
          </componentFailures>
          <componentFailures>
            <changed>false</changed>
            <componentType>FlexiPage</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:28.000Z</createdDate>
            <deleted>false</deleted>
            <fileName>flexipages/Advisor_Link_Group_List.flexipage</fileName>
            <fullName>Advisor_Link_Group_List</fullName>
            <problem>id does not exist</problem>
            <problemType>Error</problemType>
            <success>false</success>
          </componentFailures>
          <componentFailures>
            <changed>false</changed>
            <componentType>FlexiPage</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:28.000Z</createdDate>
            <deleted>false</deleted>
            <fileName>flexipages/Advisor_Link_napili_themeLayout_home.flexipage</fileName>
            <fullName>Advisor_Link_napili_themeLayout_home</fullName>
            <problem>id does not exist</problem>
            <problemType>Error</problemType>
            <success>false</success>
          </componentFailures>
          <componentFailures>
            <changed>false</changed>
            <componentType>AuraDefinitionBundle</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:28.000Z</createdDate>
            <deleted>false</deleted>
            <fileName>aura/lookupPill</fileName>
            <fullName>lookupPill</fullName>
            <problem>This lightning component bundle is referenced elsewhere in salesforce.com.  Remove the usage and try again. : Lightning Component Bundle "c:autocompleteTest" - APPLICATION - 0AdB0000000ovDi.</problem>
            <problemType>Error</problemType>
            <success>false</success>
          </componentFailures>
          <componentFailures>
            <changed>false</changed>
            <componentType>AuraDefinitionBundle</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:28.000Z</createdDate>
            <deleted>false</deleted>
            <fileName>aura/autocompleteOption</fileName>
            <fullName>autocompleteOption</fullName>
            <problem>This lightning component bundle is referenced elsewhere in salesforce.com.  Remove the usage and try again. : Lightning Component Bundle "c:autocompleteTest" - APPLICATION - 0AdB0000000ovDi.</problem>
            <problemType>Error</problemType>
            <success>false</success>
          </componentFailures>
          <componentFailures>
            <changed>false</changed>
            <componentType>AuraDefinitionBundle</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:28.000Z</createdDate>
            <deleted>false</deleted>
            <fileName>aura/autocompleteSelectListOption</fileName>
            <fullName>autocompleteSelectListOption</fullName>
            <problem>This lightning component bundle is referenced elsewhere in salesforce.com.  Remove the usage and try again. : Lightning Component Bundle "c:autocompleteTest" - APPLICATION - 0AdB0000000ovDi.</problem>
            <problemType>Error</problemType>
            <success>false</success>
          </componentFailures>
          <componentFailures>
            <changed>false</changed>
            <componentType>StaticResource</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:28.000Z</createdDate>
            <deleted>false</deleted>
            <fileName>staticresources/siteAsset_c026449691e7463c9abe14f98e87c5f1.resource</fileName>
            <fullName>siteAsset_c026449691e7463c9abe14f98e87c5f1</fullName>
            <problem>id does not exist</problem>
            <problemType>Error</problemType>
            <success>false</success>
          </componentFailures>
          <componentFailures>
            <changed>false</changed>
            <componentType>AuraDefinitionBundle</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:28.000Z</createdDate>
            <deleted>false</deleted>
            <fileName>aura/autocomplete</fileName>
            <fullName>autocomplete</fullName>
            <problem>This lightning component bundle is referenced elsewhere in salesforce.com.  Remove the usage and try again. : Lightning Component Bundle "c:autocompleteTest" - APPLICATION - 0AdB0000000ovDi.</problem>
            <problemType>Error</problemType>
            <success>false</success>
          </componentFailures>
          <componentFailures>
            <changed>false</changed>
            <componentType>AuraDefinitionBundle</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:28.000Z</createdDate>
            <deleted>false</deleted>
            <fileName>aura/dataProviderInterface</fileName>
            <fullName>dataProviderInterface</fullName>
            <problem>This lightning component bundle is referenced elsewhere in salesforce.com.  Remove the usage and try again. : Lightning Component Bundle "c:autocompleteSObjectProvider" - COMPONENT - 0AdB0000000ozI6. This lightning component bundle is referenced elsewhere in salesforce.com.  Remove the usage and try again. : Lightning Component Bundle "c:dummyDataProvider" - COMPONENT - 0AdB0000000ovDn. This lightning component bundle is referenced elsewhere in salesforce.com.  Remove the usage and try again. : Lightning Component Bundle "c:autocompleteTest" - APPLICATION - 0AdB0000000ovDi.</problem>
            <problemType>Error</problemType>
            <success>false</success>
          </componentFailures>
          <componentFailures>
            <changed>false</changed>
            <componentType>AuraDefinitionBundle</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:28.000Z</createdDate>
            <deleted>false</deleted>
            <fileName>aura/lookup</fileName>
            <fullName>lookup</fullName>
            <problem>This lightning component bundle is referenced elsewhere in salesforce.com.  Remove the usage and try again. : Lightning Component Bundle "c:autocompleteTest" - APPLICATION - 0AdB0000000ovDi.</problem>
            <problemType>Error</problemType>
            <success>false</success>
          </componentFailures>
          <componentFailures>
            <changed>false</changed>
            <componentType>AuraDefinitionBundle</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:28.000Z</createdDate>
            <deleted>false</deleted>
            <fileName>aura/autocompleteContext</fileName>
            <fullName>autocompleteContext</fullName>
            <problem>This lightning component bundle is referenced elsewhere in salesforce.com.  Remove the usage and try again. : Lightning Component Bundle "c:autocompleteTest" - APPLICATION - 0AdB0000000ovDi.</problem>
            <problemType>Error</problemType>
            <success>false</success>
          </componentFailures>
          <componentFailures>
            <changed>false</changed>
            <componentType>AuraDefinitionBundle</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:28.000Z</createdDate>
            <deleted>false</deleted>
            <fileName>aura/lookupPillRemove</fileName>
            <fullName>lookupPillRemove</fullName>
            <problem>This lightning component bundle is referenced elsewhere in salesforce.com.  Remove the usage and try again. : Lightning Component Bundle "c:autocompleteTest" - APPLICATION - 0AdB0000000ovDi.</problem>
            <problemType>Error</problemType>
            <success>false</success>
          </componentFailures>
          <componentSuccesses>
            <changed>false</changed>
            <componentType>CommunityTemplateDefinition</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:26.000Z</createdDate>
            <deleted>true</deleted>
            <fileName>communityTemplateDefinitions/Advisor_Link.communityTemplateDefinition</fileName>
            <fullName>Advisor_Link</fullName>
            <id>05jB000000000hvIAA</id>
            <success>true</success>
          </componentSuccesses>
          <componentSuccesses>
            <changed>false</changed>
            <componentType>CustomMetadata</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:27.000Z</createdDate>
            <deleted>true</deleted>
            <fileName>customMetadata/Appt_Location.in_person.md</fileName>
            <fullName>Appt_Location.in_person</fullName>
            <id>m00B00000000NGvIAM</id>
            <success>true</success>
          </componentSuccesses>
          <componentSuccesses>
            <changed>false</changed>
            <componentType>CustomMetadata</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:27.000Z</createdDate>
            <deleted>true</deleted>
            <fileName>customMetadata/Appt_Location.online.md</fileName>
            <fullName>Appt_Location.online</fullName>
            <id>m00B00000000NGwIAM</id>
            <success>true</success>
          </componentSuccesses>
          <componentSuccesses>
            <changed>false</changed>
            <componentType>ApexClass</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:27.000Z</createdDate>
            <deleted>true</deleted>
            <fileName>classes/Default_TEST.cls</fileName>
            <fullName>Default_TEST</fullName>
            <id>01pB00000012VbkIAE</id>
            <success>true</success>
          </componentSuccesses>
          <componentSuccesses>
            <changed>true</changed>
            <componentType/>
            <created>false</created>
            <createdDate>2017-01-18T02:30:28.000Z</createdDate>
            <deleted>false</deleted>
            <fileName>package.xml</fileName>
            <fullName>package.xml</fullName>
            <success>true</success>
          </componentSuccesses>
          <componentSuccesses>
            <changed>false</changed>
            <componentType>CustomObject</componentType>
            <created>false</created>
            <createdDate>2017-01-18T02:30:28.000Z</createdDate>
            <deleted>true</deleted>
            <fileName>objects/Appt_Location__mdt.object</fileName>
            <fullName>Appt_Location__mdt</fullName>
            <id>01IB0000000MYFmMAO</id>
            <success>true</success>
          </componentSuccesses>
          <runTestResult>
            <numFailures>0</numFailures>
            <numTestsRun>0</numTestsRun>
            <totalTime>0.0</totalTime>
          </runTestResult>
        </details>
        <done>true</done>
        <id>0AfB00000098UAPKA2</id>
        <ignoreWarnings>true</ignoreWarnings>
        <lastModifiedDate>2017-01-18T02:30:28.000Z</lastModifiedDate>
        <numberComponentErrors>31</numberComponentErrors>
        <numberComponentsDeployed>5</numberComponentsDeployed>
        <numberComponentsTotal>36</numberComponentsTotal>
        <numberTestErrors>0</numberTestErrors>
        <numberTestsCompleted>0</numberTestsCompleted>
        <numberTestsTotal>0</numberTestsTotal>
        <rollbackOnError>true</rollbackOnError>
        <runTestsEnabled>false</runTestsEnabled>
        <startDate>2017-01-18T02:30:24.000Z</startDate>
        <status>Failed</status>
        <success>false</success>
      </result>
    </checkDeployStatusResponse>
  </soapenv:Body>
</soapenv:Envelope>
```

**Comment by jlantz** [comment]
I'm going to try to resolve this one today.  It came up as a result of me trying to provide more output when there are component failures instead of just echoing the `<problem>` element without context like filename or line number.  Problem is, not all `componentFailures` have a line number.

**Comment by dospromptman** [comment]
yes, `lineNumber` is optional, as are many other elements of `componentFailures`.  At least according to the WSDL.

**Comment by jlantz** [comment]
Actually, this was fixed yesterday and released this morning :)  I just noticed a build that properly output the component failures without line numbers.  `pip install --upgrade cumulusci` and it should work.
