### ISSUE TITLE
Unicode problems

### ISSUE THREAD

**Issue by rodrigosiviero** [SalesforceFoundation/CumulusCI#271]
Hi, I'm trying to create a package.xml using update_package_xml task from my src folder but I'm having a trouble with unicode:

`(cumulusci_dev) rodrigosiviero@rodrigo-siviero~/projetos/salesforce (master ⬆ ✗) » cci task run update_package_xml --org adi
2017-03-23 08:43:44: Beginning task: UpdatePackageXml
2017-03-23 08:43:44:
2017-03-23 08:43:44: Generating src/package.xml from metadata in src
Traceback (most recent call last):
  File "/Users/rodrigosiviero/cumulusci_dev/bin/cci", line 11, in <module>
    sys.exit(cli())
  File "/Users/rodrigosiviero/cumulusci_dev/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rodrigosiviero/cumulusci_dev/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/rodrigosiviero/cumulusci_dev/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rodrigosiviero/cumulusci_dev/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rodrigosiviero/cumulusci_dev/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rodrigosiviero/cumulusci_dev/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/rodrigosiviero/cumulusci_dev/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Users/rodrigosiviero/cumulusci_dev/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/rodrigosiviero/cumulusci_dev/lib/python2.7/site-packages/cumulusci/cli/cli.py", line 606, in task_run
    task()
  File "/Users/rodrigosiviero/cumulusci_dev/lib/python2.7/site-packages/cumulusci/core/tasks.py", line 80, in __call__
    self.result = self._run_task()
  File "/Users/rodrigosiviero/cumulusci_dev/lib/python2.7/site-packages/cumulusci/tasks/metadata/package.py", line 370, in _run_task
    package_xml = self.package_xml()
  File "/Users/rodrigosiviero/cumulusci_dev/lib/python2.7/site-packages/cumulusci/tasks/metadata/package.py", line 58, in __call__
    return self.render_xml()
  File "/Users/rodrigosiviero/cumulusci_dev/lib/python2.7/site-packages/cumulusci/tasks/metadata/package.py", line 111, in render_xml
    type_xml = parser()
  File "/Users/rodrigosiviero/cumulusci_dev/lib/python2.7/site-packages/cumulusci/tasks/metadata/package.py", line 135, in __call__
    return self.render_xml()
  File "/Users/rodrigosiviero/cumulusci_dev/lib/python2.7/site-packages/cumulusci/tasks/metadata/package.py", line 189, in render_xml
    output.append(u'        <members>{0}</members>'.format(member))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 35: ordinal not in range(128)`

is there anything that I can do about it?

**Comment by cpolcyn** [comment]
@rodrigosiviero thanks for the report. I just submitted a fix that you can test out in branch `issue-271` or wait for it to be merged to master (should be soon).

**Comment by rodrigosiviero** [comment]
Hi @cpolcyn thanks for the quick fix, I'm gonna fix as soon it's merged :)
