### ISSUE TITLE
Update Package XML Managed fails on StandardValueSets

### ISSUE THREAD

**Issue by craigargh** [SalesforceFoundation/CumulusCI#310]
The `update_package_xml_managed` task fails when there is StandardValueSet metadata in the src folder.

```
Generating src/package.xml from metadata in src
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\cci.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\cumulusci\cli\cli.py", line 606, in task_run
    task()
  File "c:\python27\lib\site-packages\cumulusci\core\tasks.py", line 95, in __call__
    self.result = self._run_task()
  File "c:\python27\lib\site-packages\cumulusci\tasks\metadata\package.py", line 372, in _run_task
    package_xml = self.package_xml()
  File "c:\python27\lib\site-packages\cumulusci\tasks\metadata\package.py", line 58, in __call__
    self.parse_types()
  File "c:\python27\lib\site-packages\cumulusci\tasks\metadata\package.py", line 71, in parse_types
    raise MetadataParserMissingError('No parser configuration found for subdirectory %s' % item)
cumulusci.tasks.metadata.package.MetadataParserMissingError: No parser configuration found for subdirectory standardValueSets
```

**Comment by scottHen** [comment]
Also fails with flows metadata in the src folder.

**Comment by jlantz** [comment]
@craigargh can you try the StandardValueSets again with beta32?  I think this commit should have fixed this issue by adding a mapping:
https://github.com/SalesforceFoundation/CumulusCI/commit/f766b0290335f5053e689ae91e0811af4bc15db6

@scottHen I've created a separate issue for mapping Flows metadata.

**Comment by jlantz** [comment]
I don't have an org with StandardValueSets to test this fix but it should work.  I'm going to close the issue but please reopen if the problem still occurs.

**Comment by scottHen** [comment]
I have tested it and it works. 
Thank you
