### ISSUE TITLE
Update of None package.xml: Error: Invalid version specified:1.0 (Beta 21)

### ISSUE THREAD

**Issue by Szandor72** [SalesforceFoundation/CumulusCI#317]
Hello there,

since we reached Beta 20 - we're hitting error below. We haven't changed anything in the configuration.

Googling revealed only a thread from 2008 about this particular error. Wouldn't know how to fix/prevent it. 

```
2017-05-15 13:42:37: Running task: install_managed_beta
2017-05-15 13:42:37: Installing latest beta release: 1.0 (Beta 21)
2017-05-15 13:42:38: Options:
2017-05-15 13:42:38:   retry_interval_add: 30
2017-05-15 13:42:38:   retries: 5
2017-05-15 13:42:38:   version: 1.0 (Beta 21)
2017-05-15 13:42:38:   namespace: apo_test_pkg01
2017-05-15 13:42:38:   retry_interval: 5
2017-05-15 13:42:38: Beginning task: InstallPackageVersion
2017-05-15 13:42:38: 
2017-05-15 13:42:38: Pending
2017-05-15 13:42:39: [Done]
2017-05-15 13:42:40: [Failed]: Update of None package.xml: Error: Invalid version specified:1.0 (Beta 21)
2017-05-15 13:42:40: Task failed: install_managed_beta
2017-05-15 13:42:40: Failing flow due to exception in task
Traceback (most recent call last):
  File "/home/ubuntu/virtualenvs/venv-2.7.12/lib/python2.7/site-packages/cumulusci/core/flows.py", line 136, in _run_task
    task()
  File "/home/ubuntu/virtualenvs/venv-2.7.12/lib/python2.7/site-packages/cumulusci/core/tasks.py", line 95, in __call__
    self.result = self._run_task()
  File "/home/ubuntu/virtualenvs/venv-2.7.12/lib/python2.7/site-packages/cumulusci/tasks/salesforce.py", line 385, in _run_task
    self._retry()
  File "/home/ubuntu/virtualenvs/venv-2.7.12/lib/python2.7/site-packages/cumulusci/core/tasks.py", line 113, in _retry
    self._try()
  File "/home/ubuntu/virtualenvs/venv-2.7.12/lib/python2.7/site-packages/cumulusci/tasks/salesforce.py", line 389, in _try
    api()
  File "/home/ubuntu/virtualenvs/venv-2.7.12/lib/python2.7/site-packages/cumulusci/salesforce_api/metadata.py", line 53, in __call__
    return self._process_response(response)
  File "/home/ubuntu/virtualenvs/venv-2.7.12/lib/python2.7/site-packages/cumulusci/salesforce_api/metadata.py", line 463, in _process_response
    raise MetadataComponentFailure(log, response)
MetadataComponentFailure: Update of None package.xml: Error: Invalid version specified:1.0 (Beta 21)
Error: Failed: MetadataComponentFailure
```

**Comment by jlantz** [comment]
The error message "Update of None package.xml" is coming from CumulusCI's code.  The None is supposed to be the metadata type but in this instance it's saying the issue is in the package.xml file which doesn't really have a metadata type.  The rest of the error string starting with "Error: Invalid version..." is coming from the MDAPI directly and CumulusCI is just passing it through.

I can't think of any reason why going from Beta 20 to Beta 21 would cause this problem so I'm presuming the problem lies elsewhere.

Is this a version you just uploaded?  If so, does it work if you try running the install_managed_beta task 15 minutes later?  I know that sometimes a newly uploaded package isn't available on all pods.  CumulusCI attempts to detect the package unavailable error messages and retry the request a few times to work around this.  It doesn't look like we handle this particular error message but if that's the issue we could easily add handling for it.

**Comment by Szandor72** [comment]
Cheers. And more so for the quick response. Will check asap.

Error started occuring after Beta 19.

**Comment by Szandor72** [comment]
Thank you again, Jason - uploading beta v 22 has worked without issues now. Will keep an eye open.

**Comment by Szandor72** [comment]
I could confirm it has nothing to do with version number

`[Failed]: Update of None package.xml: Error: Invalid version specified:1.1 (Beta 3)` 

Locally, this error does not occur when running `cci flow run ci_beta --org beta`. It does however pop up in CircleCI.

**Comment by jlantz** [comment]
Well, I just had a build fail with the same error on a different package:
https://mrbelvedereci.herokuapp.com/builds/2829

I'm going to continue to investigate and might have a workaround in a new release if I can figure one out.

Are you using scratch orgs in your builds?

**Comment by force2b** [comment]
Interesting. I just created that branch, but haven't even made a commit yet.

**Comment by Szandor72** [comment]
I have noticed CircleCI starting another build without commit as well

![image](https://cloud.githubusercontent.com/assets/16804218/26078944/6845be5a-39c1-11e7-9cdf-fb9fa92a9446.png)

**Comment by jlantz** [comment]
@Szandor72 This one turns out to be my bad.  beta33 had a bug that was causing errors in installing packages.  It would have only caused failures when there was a need to change the version of an installed package hence why it was intermittent between environments.

beta34 has the fix and is now live.  Sorry for the confusion and thanks for reporting it.
