### ISSUE TITLE
Task generate Apex Docs fails with java.io.FileNotFoundException: None (No such file or directory)

### ISSUE THREAD

**Issue by Szandor72** [SalesforceFoundation/CumulusCI#377]
We tried running generate Apex Doc on a Mac and get the error below.

Also tried running apexdoc.jar manually but that fails with a similar issue - apexdocs seems unable to scan src/classes albeit present. 

On a sidenote: cci seems to try running apexdoc using bash which leads to a second issue on windows machines. I'd love to see this addressed but understand if not. In this case, I'd like to suggest add supported Operating Systems to the Readme. 

```
(cumulusci_venv) 17:42:49 ~/dev/ws/project --> ls
circle.yml	circleDX.yml	config		cumulusci.yml	  docs		force.json	src		tasks		tests		unpackaged

(cumulusci_venv) 17:42:49 ~/dev/ws/project/src/classes --> ls
myClass.cls    myClass.cls-meta.xml

(cumulusci_venv) 17:42:49 ~/dev/ws/project --> cci task run generate_apex_docs -o tag "beta02" -o out_dir "./docs"
2017-07-25 17:43:03: Beginning task: GenerateApexDocs
2017-07-25 17:43:03: 
java.io.FileNotFoundException: None (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at org.salesforce.apexdoc.FileManager.parseFile(Unknown Source)
	at org.salesforce.apexdoc.FileManager.parseHTMLFile(Unknown Source)
	at org.salesforce.apexdoc.ApexDoc.RunApexDoc(Unknown Source)
	at org.salesforce.apexdoc.ApexDoc.main(Unknown Source)
java.io.FileNotFoundException: None (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at org.salesforce.apexdoc.FileManager.parseFile(Unknown Source)
	at org.salesforce.apexdoc.FileManager.parseHTMLFile(Unknown Source)
	at org.salesforce.apexdoc.ApexDoc.RunApexDoc(Unknown Source)
	at org.salesforce.apexdoc.ApexDoc.main(Unknown Source)
java.lang.NullPointerException
	at org.salesforce.apexdoc.ClassModel$1.compare(Unknown Source)
	at org.salesforce.apexdoc.ClassModel$1.compare(Unknown Source)
	at java.util.TimSort.binarySort(TimSort.java:296)
	at java.util.TimSort.sort(TimSort.java:221)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:175)
	at org.salesforce.apexdoc.ClassModel.getMethodsSorted(Unknown Source)
	at org.salesforce.apexdoc.FileManager.htmlForClassModel(Unknown Source)
	at org.salesforce.apexdoc.FileManager.makeFile(Unknown Source)
	at org.salesforce.apexdoc.FileManager.createDoc(Unknown Source)
	at org.salesforce.apexdoc.ApexDoc.RunApexDoc(Unknown Source)
	at org.salesforce.apexdoc.ApexDoc.main(Unknown Source)
2017-07-25 17:43:08: null
2017-07-25 17:43:08: ApexDoc - a tool for generating documentation from Salesforce Apex code class files.
2017-07-25 17:43:08: 
2017-07-25 17:43:08:     Invalid Arguments detected.  The correct syntax is:
2017-07-25 17:43:08: 
2017-07-25 17:43:08: apexdoc -s <source_directory> [-t <target_directory>] [-g <source_url>] [-h <homefile>] [-a <authorfile>] [-p <scope>]
2017-07-25 17:43:08: 
2017-07-25 17:43:08: <source_directory> - The folder location which contains your apex .cls classes
2017-07-25 17:43:08: <target_directory> - Optional. Specifies your target folder where documentation will be generated.
2017-07-25 17:43:08: <source_url> - Optional. Specifies a URL where the source is hosted (so ApexDoc can provide links to your source).
2017-07-25 17:43:08: <homefile> - Optional. Specifies the html file that contains the contents for the home page's content area.
2017-07-25 17:43:08: <authorfile> - Optional. Specifies the text file that contains project information for the documentation header.
2017-07-25 17:43:08: <scope> - Optional. Semicolon seperated list of scopes to document.  Defaults to 'global;public'.
2017-07-25 17:43:08: Return code: 255
stderr: None
Traceback (most recent call last):
  File "/Users/myuser/cumulusci_venv/bin/cci", line 11, in <module>
    sys.exit(cli())
  File "/Users/myuser/cumulusci_venv/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/myuser/cumulusci_venv/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/myuser/cumulusci_venv/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/myuser/cumulusci_venv/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/myuser/cumulusci_venv/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/myuser/cumulusci_venv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/myuser/cumulusci_venv/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Users/myuser/cumulusci_venv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/myuser/cumulusci_venv/lib/python2.7/site-packages/cumulusci/cli/cli.py", line 641, in task_run
    task()
  File "/Users/myuser/cumulusci_venv/lib/python2.7/site-packages/cumulusci/core/tasks.py", line 95, in __call__
    self.result = self._run_task()
  File "/Users/myuser/cumulusci_venv/lib/python2.7/site-packages/cumulusci/tasks/apexdoc.py", line 52, in _run_task
    self._run_command({})
  File "/Users/myuser/cumulusci_venv/lib/python2.7/site-packages/cumulusci/tasks/command.py", line 85, in _run_command
    self._handle_returncode(p.returncode, p.stderr)
  File "/Users/myuser/cumulusci_venv/lib/python2.7/site-packages/cumulusci/tasks/command.py", line 69, in _handle_returncode
    raise CommandException(message)
cumulusci.core.exceptions.CommandException: Return code: 255
stderr: None
```

**Comment by cpolcyn** [comment]
Was able to run this locally against CumulusCI-Test with no issues. Here is how the command is constructed in GenerateApexDocs class:

```python
self.options['command'] = ('java ' +
            '-jar {} -s {} -t {} -g {} -h {} -a {} -p "{}"'.format(
                self.jar_path,
                os.path.join(self.project_config.repo_root, 'src', 'classes'),
                self.options['out_dir'],
                self.source_url,
                self.project_config.project__apexdoc__homepage,
                self.project_config.project__apexdoc__banner,
                self.project_config.project__apexdoc__scope,
            )
        )
```

Maybe one of these values is None for you and the formatting placeholder is skipped, resulting in malformed options? You can run in debug mode to see the command that is formed.

RE: Mac vs Win – Command does specify `executable='/bin/bash'` in the call to subprocess.Popen() and I'm not sure why. Will file a separate issue for that.

**Comment by cpolcyn** [comment]
https://github.com/SalesforceFoundation/CumulusCI/issues/379

**Comment by cpolcyn** [comment]
@Szandor72 there is some corresponding config in cumulusci.yml to do for the command to work, for example:

https://github.com/SalesforceFoundation/HEDAP/blob/master/cumulusci.yml#L11

I'm guessing this was missing when you tried. Please let me know if you get it working so we can close this out. I'll add some info about the config to the task description.

**Comment by cpolcyn** [comment]
After thinking on it some more, I see that homepage and header are not required args for apexdoc so I will make those optional in the command construction.
