### ISSUE TITLE
Task upload_production throwing odd errors

### ISSUE THREAD

**Issue by Joble** [SalesforceFoundation/CumulusCI#392]
I am attempting to use  _cumulusci task run upload_production -o name "Pardot Package v3.45" -o namespace pi -o production True_ with CCI 2.0.0-beta56. When I do, I get the error below:

`$ cumulusci task run upload_production -o name "Pardot Package v3.45" -o namespace pi -o production True
Traceback (most recent call last):
  File "/usr/local/bin/cumulusci", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'cumulusci' distribution was not found and is required by the application`

**Comment by cpolcyn** [comment]
I just used the task to create HEDA 1.39 and it worked fine. I'm using local development code (latest) instead of pypi package.

**Comment by Joble** [comment]
I'll give it another try a bit later to see if using the _cci_ command does the trick.

**Comment by Joble** [comment]
@cpolcyn I gave your suggestion a try and use the _cci_ command. It executed correctly and created a new package version.
