### ISSUE TITLE
Not able to Authorize Cumulus CI when I use custom domain or Sandbox

### ISSUE THREAD

**Issue by LovelIncapsulate** [SalesforceFoundation/CumulusCI#401]
When I try to connect and Authorize Cumumlus CI with Sandbox, it throws error
C:\Users\Documents\Cumulus CI>cci org connect devincaplp
Launching web browser for URL https://login.salesforce.com/services/oauth2/authorize?response_type=code&client_id=3MVG9ic.6IFhNpPqarq99Thj82e7mifl4i.XXXXXXXXXXXXXXXXXXXXXXX&redirect_uri=http://localhost:8080/callback&scope=web%20full%20refresh_token&prompt=login
Spawning HTTP server at http://localhost:8080/callback with timeout of 300 seconds.
If you are unable to log in to Salesforce you can press ctrl+c to kill the server and return to the command line.

----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 64590)
Traceback (most recent call last):
  File "c:\python27\lib\SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "c:\python27\lib\SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "c:\python27\lib\SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\python27\lib\SocketServer.py", line 651, in __init__
    self.handle()
  File "c:\python27\lib\BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "c:\python27\lib\BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "c:\python27\lib\site-packages\cumulusci\oauth\salesforce.py", line 85, in do_GET
    self.parent.response = self.parent.oauth_api.get_token(code)
  File "c:\python27\lib\site-packages\cumulusci\oauth\salesforce.py", line 55, in get_token
    return self._request_token(data)
  File "c:\python27\lib\site-packages\cumulusci\oauth\salesforce.py", line 36, in _request_token
    raise RequestOauthTokenError(message, response)
RequestOauthTokenError: 400: {"error":"invalid_grant","error_description":"authentication failure"}
----------------------------------------
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\cci.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\cumulusci\cli\cli.py", line 399, in org_connect
    oauth_dict = oauth_capture()
  File "c:\python27\lib\site-packages\cumulusci\oauth\salesforce.py", line 120, in __call__
    self._check_response(self.response)
  File "c:\python27\lib\site-packages\cumulusci\oauth\salesforce.py", line 124, in _check_response
    if response.status_code == httplib.OK:
AttributeError: 'NoneType' object has no attribute 'status_code'

C:\Users\INCAPSULATE\Documents\Cumulus CI>cci org info devincaplp
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\cci.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\cumulusci\cli\cli.py", line 430, in org_info
    org_config = config.keychain.get_org(org_name)
  File "c:\python27\lib\site-packages\cumulusci\core\keychain.py", line 115, in get_org
    self._raise_org_not_found(name)
  File "c:\python27\lib\site-packages\cumulusci\core\keychain.py", line 348, in _raise_org_not_found
    name
cumulusci.core.exceptions.OrgNotFound: Org information could not be found.  Expected to find encrypted file at C:\Users\INCAPSULATE\.cumulusci\DevIncapLp/devincaplp.org
-------------------------------------------------------------------------------------------------------------------
Instead, the above URL should point to custom URL  or Sand box URL which is https://test.salesforce.com instead of 
https://login.salesforce.com/services/oauth2/authorize?response_type=code&client_id=3MVG9ic.6IFhNpPqarq99Thj82e7mifl4i.XXXXXXXXXXXX&redirect_uri=http://localhost:8080/callback&scope=web%20full%20refresh_token&prompt=login

**Comment by cdcarter** [comment]
can you try

```
cci org connect devincaplp --login-url=https://test.salesforce.com 
```

**Comment by LovelIncapsulate** [comment]
Thanks a ton will try and get back to you

**Comment by triestelaporte** [comment]
This worked for me, but I had to come here to find the --login-url option, as I couldn't find it in the -help or documentation.  Super worth a quick add.  Thanks!

**Comment by cdcarter** [comment]
it's in the interactive help but not very well written:
```
(cci-q3) ➜  NPSP git:(feature/dave-bdi-perf) ✗ cci org connect --help
Usage: cci org connect [OPTIONS] ORG_NAME

  Connects a new org's credentials using OAuth Web Flow

Options:
  --sandbox         If set, connects to a Salesforce sandbox org
  --login-url TEXT  If set, login to this hostname.
  --default         If set, sets the connected org as the new default org
  --global-org      Set True if org should be used by any project
  --help            Show this message and exit.
```
I'm going to close this issue and open a doc bug
