### ISSUE TITLE
GitHub tasks crash because repo object is None

### ISSUE THREAD

**Issue by cpolcyn** [SalesforceFoundation/CumulusCI#408]
```bash
$ cci task run github_clone_tag -o src_tag beta/1.1-Beta_1 -o tag release/1.1
2017-08-29 10:58:14: Beginning task: CloneTag
2017-08-29 10:58:14: 
Traceback (most recent call last):
  File "/Users/cpolcyn/venvs/CumulusCI/bin/cci", line 11, in <module>
    load_entry_point('cumulusci', 'console_scripts', 'cci')()
  File "/Users/cpolcyn/venvs/CumulusCI/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cpolcyn/venvs/CumulusCI/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/cpolcyn/venvs/CumulusCI/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cpolcyn/venvs/CumulusCI/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cpolcyn/venvs/CumulusCI/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cpolcyn/venvs/CumulusCI/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/cpolcyn/venvs/CumulusCI/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Users/cpolcyn/venvs/CumulusCI/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/cpolcyn/dev/CumulusCI/cumulusci/cli/cli.py", line 715, in task_run
    task()
  File "/Users/cpolcyn/dev/CumulusCI/cumulusci/core/tasks.py", line 109, in __call__
    self.result = self._run_task()
  File "/Users/cpolcyn/dev/CumulusCI/cumulusci/tasks/github/tag.py", line 21, in _run_task
    ref = repo.ref('tags/{}'.format(self.options['src_tag']))
AttributeError: 'NoneType' object has no attribute 'ref'
```

**Comment by cpolcyn** [comment]
Seeing this with all github tasks.

**Comment by cpolcyn** [comment]
This was due to misconfiguration of the GitHub Personal Access Token. Closing as invalid

**Comment by cdcarter** [comment]
we should probably raise a better error if we can't auth to github?
