### ISSUE TITLE
Error when running "cci task run uninstall_src"

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/CumulusCI#417]
When running `cci task run uninstall_src`, I get the following error:

```
2017-09-01 11:16:52: 
Traceback (most recent call last):
  File "/Users/ceiroa/cumulusci_venv/bin/cci", line 11, in <module>
    sys.exit(cli())
  File "/Users/ceiroa/cumulusci_venv/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ceiroa/cumulusci_venv/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/ceiroa/cumulusci_venv/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ceiroa/cumulusci_venv/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ceiroa/cumulusci_venv/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ceiroa/cumulusci_venv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/ceiroa/cumulusci_venv/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Users/ceiroa/cumulusci_venv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/ceiroa/cumulusci_venv/lib/python2.7/site-packages/cumulusci/cli/cli.py", line 715, in task_run
    task()
  File "/Users/ceiroa/cumulusci_venv/lib/python2.7/site-packages/cumulusci/core/tasks.py", line 109, in __call__
    self.result = self._run_task()
  File "/Users/ceiroa/cumulusci_venv/lib/python2.7/site-packages/cumulusci/tasks/salesforce.py", line 69, in _run_task
    api = self._get_api()
  File "/Users/ceiroa/cumulusci_venv/lib/python2.7/site-packages/cumulusci/tasks/salesforce.py", line 769, in _get_api
    api = self.api_class(self, package_zip(), purge_on_delete=self.options['purge_on_delete'])
KeyError: 'purge_on_delete'
```

**Comment by cdcarter** [comment]
`UninstallLocal` doesn't declare it's task options even though its wired up in YAML. either we should set task_options on the class, or only use `UninstallLocal` as a superclass.
