### ISSUE TITLE
cci doesn't read projects section for scratch org def

### ISSUE THREAD

**Issue by SalesforceRocks** [SalesforceFoundation/CumulusCI#518]
I have the following in my cumulusci.yml:

orgs:
    scratch:
        dev:
            config_file: config/dev.json
            days: 7
        feature:
            config_file: config/feature.json
        beta:
            config_file: config/beta.json
        release:
            config_file: config/release.json

But when issuing cci org info dev from the terminal (MacOs) I get:

Creating scratch org with command sfdx force:org:create -f orgs/dev.json -n --durationdays 1 -a growpromoter__dev 
ERROR:  ENOENT: no such file or directory, open 'orgs/dev.json'.
Error: ScratchOrgException: Failed to create scratch org: 

Changing the cumulusci.yml to use orgs/dev.json instead doesn't seem to resolve the issue. Deleting the scratch org with sfdx force:org:delete only makes the issue much worse:

Return code: 1
2017-11-26 15:01:18: {"message":"No org configuration found for name test-ijzsaipyvlej@growpromoter.net","status":1,"stack":"NoOrgFound: No org configuration found for name test-ijzsaipyvlej@growpromoter.net\n    at _buildNoOrgError (/Users/jaapbranderhorst/.local/share/sfdx/client/node_modules/salesforce-alm/dist/lib/scratchOrgApi.js:93:27)\n    at Promise.resolve.then.then.catch (/Users/jaapbranderhorst/.local/share/sfdx/client/node_modules/salesforce-alm/dist/lib/scratchOrgApi.js:491:39)\n    at tryCatcher (/Users/jaapbranderhorst/.local/share/sfdx/client/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/Users/jaapbranderhorst/.local/share/sfdx/client/node_modules/bluebird/js/release/promise.js:510:31)\n    at Promise._settlePromise (/Users/jaapbranderhorst/.local/share/sfdx/client/node_modules/bluebird/js/release/promise.js:567:18)\n    at Promise._settlePromise0 (/Users/jaapbranderhorst/.local/share/sfdx/client/node_modules/bluebird/js/release/promise.js:612:10)\n    at Promise._settlePromises (/Users/jaapbranderhorst/.local/share/sfdx/client/node_modules/bluebird/js/release/promise.js:687:18)\n    at Async._drainQueue (/Users/jaapbranderhorst/.local/share/sfdx/client/node_modules/bluebird/js/release/async.js:138:16)\n    at Async._drainQueues (/Users/jaapbranderhorst/.local/share/sfdx/client/node_modules/bluebird/js/release/async.js:148:10)\n    at Immediate.Async.drainQueues (/Users/jaapbranderhorst/.local/share/sfdx/client/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:781:20)\n    at tryOnImmediate (timers.js:743:5)\n    at processImmediate [as _immediateCallback] (timers.js:714:5)","name":"NoOrgFound","warnings":[],"action":"Run the \"sfdx force:auth\" commands with --setdefaultusername to connect to an org and set it as your default org.\nRun \"force:org:create\" with --setdefaultusername to create a scratch org and set it as your default org.\nRun \"sfdx force:config:set defaultusername=<username>\" to set your default username."}
Error: ScratchOrgException: 
stderr:
{"message":"No org configuration found for name test-ijzsaipyvlej@growpromoter.net","status":1,"stack":"NoOrgFound: No org configuration found for name test-ijzsaipyvlej@growpromoter.net\n    at _buildNoOrgError (/Users/jaapbranderhorst/.local/share/sfdx/client/node_modules/salesforce-alm/dist/lib/scratchOrgApi.js:93:27)\n    at Promise.resolve.then.then.catch (/Users/jaapbranderhorst/.local/share/sfdx/client/node_modules/salesforce-alm/dist/lib/scratchOrgApi.js:491:39)\n    at tryCatcher (/Users/jaapbranderhorst/.local/share/sfdx/client/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/Users/jaapbranderhorst/.local/share/sfdx/client/node_modules/bluebird/js/release/promise.js:510:31)\n    at Promise._settlePromise (/Users/jaapbranderhorst/.local/share/sfdx/client/node_modules/bluebird/js/release/promise.js:567:18)\n    at Promise._settlePromise0 (/Users/jaapbranderhorst/.local/share/sfdx/client/node_modules/bluebird/js/release/promise.js:612:10)\n    at Promise._settlePromises (/Users/jaapbranderhorst/.local/share/sfdx/client/node_modules/bluebird/js/release/promise.js:687:18)\n    at Async._drainQueue (/Users/jaapbranderhorst/.local/share/sfdx/client/node_modules/bluebird/js/release/async.js:138:16)\n    at Async._drainQueues (/Users/jaapbranderhorst/.local/share/sfdx/client/node_modules/bluebird/js/release/async.js:148:10)\n    at Immediate.Async.drainQueues (/Users/jaapbranderhorst/.local/share/sfdx/client/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:781:20)\n    at tryOnImmediate (timers.js:743:5)\n    at processImmediate [as _immediateCallback] (timers.js:714:5)","name":"NoOrgFound","warnings":[],"action":"Run the \"sfdx force:auth\" commands with --setdefaultusername to connect to an org and set it as your default org.\nRun \"force:org:create\" with --setdefaultusername to create a scratch org and set it as your default org.\nRun \"sfdx force:config:set defaultusername=<username>\" to set your default username."}
stdout:

**Comment by jlantz** [comment]
From looking at your yaml, it should work.  Can you check to see if perhaps something is happening in the yaml merge?

cci shell
> config.project_config.orgs__scratch__dev__config_file
