### ISSUE TITLE
Set up test builds for CumulusCI

### ISSUE THREAD

**Issue by jlantz** [SalesforceFoundation/CumulusCI#52]
Related to #44 

Once the test repository exists, configure a Codeship project to test all commits of the CumulusCI repository and start using CumulusCI on CumulusCI (sort of) to create a more stable release process.

**Comment by cdcarter** [comment]
CumulusCI on Codeship is currently broken for package uploading due to what I think is the python version on codeship.

``` 
Running package_upload.py

Starting browser
/home/rof/.virtualenv/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
SNIMissingWarning
Sleeping 5 more seconds to try again.  Last attempt to connect to Selenium failed
------------------------------------------------------------
Traceback (most recent call last):
File "../CumulusCI/ci/package_upload.py", line 249, in <module>
package_upload()
File "../CumulusCI/ci/package_upload.py", line 233, in package_upload
uploader.build_package(build_name)
File "../CumulusCI/ci/package_upload.py", line 120, in build_package
driver = self.get_selenium()
File "../CumulusCI/ci/package_upload.py", line 215, in get_selenium
start_url = '%s/secur/frontdoor.jsp?sid=%s' % (self.instance_url, self.access_token)
AttributeError: 'PackageUpload' object has no attribute 'access_token'
------------------------------------------------------------
```

This is with PYTHONWARNING set to ignore

**Comment by davisagli** [comment]
These days we run CI for CumulusCI itself using a Heroku CI script that runs the CumulusCI tests and deploys the CumulusCI-Test repository.
