### ISSUE TITLE
ERROR:  ENOENT: ~/Server.key no such file: Server.key is required for DX ci_feature flow 

### ISSUE THREAD

**Issue by Szandor72** [SalesforceFoundation/CumulusCI#524]
Here's what I did locally on my Win10 machine with current cci build and enabled `defaultdevhubusername` for salesforcedx (see force:config:list below)

```
cci org remove feature
// created orgs dir, edited feature.json
cci org scratch feature feature
cci flow run ci_feature --org feature
```

Here's what I got: a not found exception for a server.key 

I will not be using any local copy of a server key but use a jwt flow for CircleCI and store the key safely.

First, though, I wanted to get this running locally.

```
C:\Users\szand\OneDrive\dev\appero-quote [master ≡ +0 ~1 -3 !]> sfdx force:config:list
=== Config
NAME                   VALUE          LOCATION
─────────────────────  ─────────────  ────────
defaultdevhubusername  sz@appero.com  Global
defaultusername        mediavelox     Global
C:\Users\szand\OneDrive\dev\appero-quote [master ≡ +0 ~1 -3 !]> cci flow run ci_feature --org feature
?[32m2017-12-14 20:56:50:?[0m ---------------------------------------
?[32m2017-12-14 20:56:50:?[0m Initializing flow class BaseFlow:
?[32m2017-12-14 20:56:50:?[0m ---------------------------------------
?[32m2017-12-14 20:56:50:?[0m
?[32m2017-12-14 20:56:50:?[0m Verifying and refreshing credentials for target org feature
?[32m2017-12-14 20:56:50:?[0m Creating scratch org with command sfdx force:org:create -f orgs/feature.json -n --durationdays 1 -a appero_Quote__feature
ERROR:  ENOENT: no such file or directory, open 'C:\Users\szand\OneDrive\dev\appero-quote\server.key'.
Traceback (most recent call last):
  File "c:\python27\Lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\szand\.virtualenvs\cumulus\Scripts\cci.exe\__main__.py", line 9, in <module>
  File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\cumulusci\cli\cli.py", line 230, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\cumulusci\cli\cli.py", line 1062, in flow_run
    handle_exception_debug(config, debug, e, no_prompt=no_prompt)
  File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\cumulusci\cli\cli.py", line 1054, in flow_run
    org_config, options, skip)
  File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\cumulusci\core\flows.py", line 33, in __init__
    self._init_flow()
  File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\cumulusci\core\flows.py", line 75, in _init_flow
    self._init_org()
  File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\cumulusci\core\flows.py", line 59, in _init_org
    self.project_config.keychain.get_connected_app()
  File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\cumulusci\core\config.py", line 1104, in refresh_oauth_token
    self.scratch_info
  File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\cumulusci\core\config.py", line 830, in scratch_info
    self.create_org()
  File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\cumulusci\core\config.py", line 1000, in create_org
    raise ScratchOrgException(message)
cumulusci.core.exceptions.ScratchOrgException: Failed to create scratch org:
```

**Comment by jlantz** [comment]
Do you get the same error just running the sfdx command directly?  This looks like something sfdx is doing.  `cci` never touches any JWT keys, at least at this point as we've never implemented JWT support

**Comment by Szandor72** [comment]
Thanks for pointing me into that obvious directions! Not related to CCI
