### ISSUE TITLE
github3.models.GitHubError: 422 Could not verify object

### ISSUE THREAD

**Issue by Szandor72** [SalesforceFoundation/CumulusCI#535]
Hello, 

running into an error I haven't encountered before and do not know how to fix since git related: 

```
[32m2018-01-11 17:45:22:[0m [31mTask failed: github_release[0m
[32m2018-01-11 17:45:22:[0m [31mFailing flow due to exception in task[0m
Traceback (most recent call last):
  File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\cumulusci\core\flows.py", line 177, in _run_task
    task()
  File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\cumulusci\core\tasks.py", line 113, in __call__
    self.result = self._run_task()
  File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\cumulusci\tasks\github\release.py", line 55, in _run_task
    lightweight = False,
  File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\github3\decorators.py", line 38, in auth_wrapper
    return func(self, *args, **kwargs)
  File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\github3\repos\repo.py", line 838, in create_tag
    json = self._json(self._post(url, data=data), 201)
  File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\github3\models.py", line 100, in _json
    if self._boolean(response, status_code, 404) and response.content:
  File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\github3\models.py", line 121, in _boolean
    raise GitHubError(response)
GitHubError: 422 Could not verify object
Traceback (most recent call last):
  File "c:\python27\Lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\szand\.virtualenvs\cumulus\Scripts\cci.exe\__main__.py", line 9, in <module>
  File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\cumulusci\cli\cli.py", line 203, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\cumulusci\cli\cli.py", line 1037, in flow_run
    handle_exception_debug(config, debug, e, no_prompt=no_prompt)
  File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\cumulusci\cli\cli.py", line 1013, in flow_run
    flow()
  File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\cumulusci\core\flows.py", line 115, in __call__
    self._run_task(flow_task_config)
  File "c:\users\szand\.virtualenvs\cumulus\lib\site-packages\cumulusci\core\flows.py", line 186, in _run_task
    raise e
github3.models.GitHubError: 422 Could not verify object
```

**Comment by cdcarter** [comment]
github was running into intermittent issues this morning, can you reproduce now?

**Comment by Szandor72** [comment]
Cannot reproduce. In additon had network issues at my workplace where this occured. Will close down as not reproducible / not cci related.

**Comment by sebastianocostanzo** [comment]
I have the same issue, I cannot get past this in my tutorial, can you help?
