### ISSUE TITLE
create_unmanaged_ee_src fails since beta80

### ISSUE THREAD

**Issue by cdcarter** [SalesforceFoundation/CumulusCI#537]
```
2018-01-11 15:29:48: Running task: create_unmanaged_ee_src
2018-01-11 15:29:48: Options:
2018-01-11 15:29:48:   path: src
2018-01-11 15:29:48:   revert_path: src.orig
2018-01-11 15:29:48: Beginning task: CreateUnmanagedEESrc
2018-01-11 15:29:48:
2018-01-11 15:29:48: Preparing metadata in src for unmanaged EE deployment
2018-01-11 15:29:48: Task failed: create_unmanaged_ee_src
2018-01-11 15:29:48: Failing flow due to exception in task
Traceback (most recent call last):
  File "/Users/christian.carter/CumulusCI/cumulusci/core/flows.py", line 191, in _run_task
    task()
  File "/Users/christian.carter/CumulusCI/cumulusci/core/tasks.py", line 113, in __call__
    self.result = self._run_task()
  File "/Users/christian.carter/CumulusCI/cumulusci/tasks/metadata/ee_src.py", line 52, in _run_task
    fname_match,
  File "/Users/christian.carter/CumulusCI/cumulusci/utils.py", line 68, in removeXmlElement
    remove_xml_element_file(name, filepath)
  File "/Users/christian.carter/CumulusCI/cumulusci/utils.py", line 76, in remove_xml_element_file
    filepath,
NameError: global name 'filepath' is not defined
```

likely due to the process_meta_xml 
likely related to #530

**Comment by jlantz** [comment]
OK, I'll take a look in the morning
