### ISSUE TITLE
Operations with scratch orgs fail with new Salesforce CLI (sfdx) on Windows

### ISSUE THREAD

**Issue by viktdm** [SalesforceFoundation/CumulusCI#611]
A colleague of mine installed the latest CumulusCI (2.0.0-beta93) and Salesforce CLI (sfdx) on his Windows 10 machine and everything was ok until we tried to create a scratch org. Any operation with a scratch org, like _cci org info dev_, would fail with the following exception. Other developers and I didn't have any problems, though--turned out that we had the older version of Salesfrorce CLI.

```
Traceback (most recent call last):
  File "C:\Python27\Lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\cumulusci\Scripts\cci.exe\__main__.py", line 9, in <module>
  File "c:\cumulusci\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\cumulusci\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\cumulusci\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\cumulusci\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\cumulusci\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\cumulusci\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\cumulusci\lib\site-packages\cumulusci\cli\cci.py", line 189, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "c:\cumulusci\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\cumulusci\lib\site-packages\cumulusci\cli\cci.py", line 676, in org_info
    org_config.refresh_oauth_token(config.keychain.get_connected_app())
  File "c:\cumulusci\lib\site-packages\cumulusci\core\config.py", line 1116, in refresh_oauth_token
    self.scratch_info
  File "c:\cumulusci\lib\site-packages\cumulusci\core\config.py", line 842, in scratch_info
    self.create_org()
  File "c:\cumulusci\lib\site-packages\cumulusci\core\config.py", line 991, in create_org
    p.run()
  File "c:\cumulusci\lib\site-packages\sarge\__init__.py", line 632, in run
    self.process = p = Popen(self.args, **self.kwargs)
  File "C:\Python27\Lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Python27\Lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```
Comparing CCI and SDFX installations, we found out that the latest SDFX version installs two files, sfdx.cmd and sdfx (without filename extension), under "C:\Program Files\Salesforce CLI\bin" (previous version of SDFX had sdfx.exe there instead) and that makes CCI fail when calling _execute_child(). As there is no executable (sfdx is just bash script), _subprocess.CreateProcess() throws the exception. Changing "sfdx" to "sfdx.cmd" in cumulusci\core\config.py commands solves the problem, but obviously this can be used only as a workaround. The proper fix would require checking (or maybe even configuring) the full path and calling the appropriate SFDX script or executable.

**Comment by jlantz** [comment]
Fixed in 2.0.4
